# Configuration for angular-robot

#options for the size plugin
size:
  # Temporary disabled until we figure out why the size status check is not being
  # updated properly. TODO(devversion): re-add once the size check is reliable.
  disabled: false
  # Name of the status that will be responsible for providing
  # artifacts that will be measured by the robot.
  circleCiStatusName: 'ci/circleci: build_release_packages'
  # Byte value of maximum allowed change in size
  maxSizeIncrease: 10000

# options for the merge plugin
merge:
  # the status will be added to your pull requests
  status:
    # set to true to disable
    disabled: false
    # the name of the status
    context: 'ci/angular: merge status'
    # text to show when all checks pass
    successText: 'All checks passed!'
    # text to show when some checks are failing
    failureText: 'The following checks are failing:'

  # the g3 status will be added to your pull requests if they include files that match the patterns
  g3Status:
    # set to true to disable
    disabled: false

  # comment that will be added to a PR when there is a conflict, leave empty or set to false to disable
  mergeConflictComment: "Hi @{{PRAuthor}}! This PR has merge conflicts due to recent upstream merges.\nPlease help to unblock it by resolving these conflicts. Thanks!"

  # label to monitor
  mergeLabel: 'pr: merge ready'

  # list of checks that will determine if the merge label can be added
  checks:
    # whether the PR shouldn't have a conflict with the base branch
    noConflict: true
    # whether the PR should have all reviews completed.
    requireReviews: false
    # list of labels that a PR needs to have, checked with a regexp.
    requiredLabels:
      - 'target: *'

    # list of labels that a PR shouldn't have, checked after the required labels with a regexp
    forbiddenLabels:
      - 'enabled'
      - 'pr: included'
      - 'pr: needs*'
      - 'presubmit failures'

  # the comment that will be added when the merge label is added despite failing checks, leave empty or set to false to disable
  # {{MERGE_LABEL}} will be replaced by the value of the mergeLabel option
  # {{PLACEHOLDER}} will be replaced by the list of failing checks
  mergeRemovedComment: 

# options for the triage plugin
triage:
  disabled: false
